# Generated by Django 5.1 on 2024-08-28 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="created_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата создания"
            ),
        ),
        migrations.AlterField(
            model_name="blog",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Содержимое"),
        ),
        migrations.AlterField(
            model_name="blog",
            name="is_published",
            field=models.BooleanField(default=False, verbose_name="Опубликовано"),
        ),
        migrations.AlterField(
            model_name="blog",
            name="name",
            field=models.CharField(max_length=50, verbose_name="Заголовок"),
        ),
        migrations.AlterField(
            model_name="blog",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="product/photo",
                verbose_name="Изображение (превью)",
            ),
        ),
        migrations.AlterField(
            model_name="blog",
            name="slug",
            field=models.CharField(max_length=50, verbose_name="Ссылка"),
        ),
        migrations.AlterField(
            model_name="blog",
            name="views",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Количество просмотров"
            ),
        ),
    ]
